--- 
- hosts: all
  become: yes 
  tasks: 
  - name: I want install apache2
    apt:
     name: apache2 
     state: present

  - name: I want install git 
    apt:
     name: git
     state: present 

  - name: I went to instaall tree 
    apt:
     name: tree
     state: present    
